2025-03-25 16:09:43,241 - custodian.policy - INFO - policy:delete_policy_unassociated resource:huaweicloud.cbr-policy region: count:1 time:1.04
2025-03-25 16:09:43,547 - custodian.policy - INFO - policy:delete_policy_unassociated action:cbrdeletepolicy resources:1 execution_time:0.31
2025-03-25 18:41:36,132 - custodian.policy - INFO - policy:delete_policy_unassociated resource:huaweicloud.cbr-policy region: count:0 time:0.92
2025-03-25 18:42:26,592 - custodian.policy - INFO - policy:delete_policy_unassociated resource:huaweicloud.cbr-policy region: count:3 time:0.00
2025-03-25 18:42:28,120 - custodian.policy - INFO - policy:delete_policy_unassociated action:cbrdeletepolicy resources:3 execution_time:1.53
2025-03-25 18:44:43,115 - custodian.policy - INFO - policy:delete_policy_unassociated resource:huaweicloud.cbr-policy region: count:3 time:0.00
2025-03-25 18:44:43,925 - custodian.huaweicloud.actions.base - ERROR - Unable to submit action against the resource - 2696bf00-e64b-4b1a-9f6b-5cee1d240eab RequestId: 1390461a303ce2683f340753dc28387f, Reason: Policy 2696bf00-e64b-4b1a-9f6b-5cee1d240eab not found.
Traceback (most recent call last):
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcore/http/http_client.py", line 127, in response_hook
    resp.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/root/custodian/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://cbr.ap-southeast-1.myhuaweicloud.com/v3/0d9da8861b80f5a32fb4c00645f2dbd7/policies/2696bf00-e64b-4b1a-9f6b-5cee1d240eab

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/huawei_custodian/cloud-custodian/tools/c7n_huaweicloud/c7n_huaweicloud/actions/base.py", line 33, in process
    self.perform_action(resource)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/root/huawei_custodian/cloud-custodian/tools/c7n_huaweicloud/c7n_huaweicloud/resources/cbr_policy.py", line 54, in perform_action
    response = client.delete_policy(request)
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcbr/v1/cbr_client.py", line 1308, in delete_policy
    return self._call_api(**http_info)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcbr/v1/cbr_client.py", line 4792, in _call_api
    return self.do_http_request(**kwargs)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcore/client.py", line 480, in do_http_request
    response = self._do_http_request_sync(request)
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcore/client.py", line 531, in _do_http_request_sync
    response = self._http_client.do_request_sync(request)
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcore/http/http_client.py", line 100, in do_request_sync
    self.response_error_hook_factory()(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcore/http/http_client.py", line 129, in response_hook
    self._exception_handler.handle_exception(httpError.request, httpError.response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcore/exceptions/exception_handler.py", line 75, in handle_exception
    raise exceptions.ClientRequestException(response.status_code, sdk_error) if response.status_code < 500 \
        else exceptions.ServerResponseException(response.status_code, sdk_error)
huaweicloudsdkcore.exceptions.exceptions.ClientRequestException: ClientRequestException - {status_code:404,request_id:1390461a303ce2683f340753dc28387f,error_code:BackupService.6000,error_msg:Policy 2696bf00-e64b-4b1a-9f6b-5cee1d240eab not found.,encoded_authorization_message:None }
2025-03-25 18:44:43,978 - custodian.huaweicloud.actions.base - ERROR - Unable to submit action against the resource - 33478244-e1cc-4ac2-9bd0-f48099fce6b0 RequestId: 285fe7843c87a0d2bf6321b8ff15caa4, Reason: Policy 33478244-e1cc-4ac2-9bd0-f48099fce6b0 not found.
Traceback (most recent call last):
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcore/http/http_client.py", line 127, in response_hook
    resp.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/root/custodian/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://cbr.ap-southeast-1.myhuaweicloud.com/v3/0d9da8861b80f5a32fb4c00645f2dbd7/policies/33478244-e1cc-4ac2-9bd0-f48099fce6b0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/huawei_custodian/cloud-custodian/tools/c7n_huaweicloud/c7n_huaweicloud/actions/base.py", line 33, in process
    self.perform_action(resource)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/root/huawei_custodian/cloud-custodian/tools/c7n_huaweicloud/c7n_huaweicloud/resources/cbr_policy.py", line 54, in perform_action
    response = client.delete_policy(request)
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcbr/v1/cbr_client.py", line 1308, in delete_policy
    return self._call_api(**http_info)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcbr/v1/cbr_client.py", line 4792, in _call_api
    return self.do_http_request(**kwargs)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcore/client.py", line 480, in do_http_request
    response = self._do_http_request_sync(request)
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcore/client.py", line 531, in _do_http_request_sync
    response = self._http_client.do_request_sync(request)
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcore/http/http_client.py", line 100, in do_request_sync
    self.response_error_hook_factory()(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcore/http/http_client.py", line 129, in response_hook
    self._exception_handler.handle_exception(httpError.request, httpError.response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/custodian/lib/python3.13/site-packages/huaweicloudsdkcore/exceptions/exception_handler.py", line 75, in handle_exception
    raise exceptions.ClientRequestException(response.status_code, sdk_error) if response.status_code < 500 \
        else exceptions.ServerResponseException(response.status_code, sdk_error)
huaweicloudsdkcore.exceptions.exceptions.ClientRequestException: ClientRequestException - {status_code:404,request_id:285fe7843c87a0d2bf6321b8ff15caa4,error_code:BackupService.6000,error_msg:Policy 33478244-e1cc-4ac2-9bd0-f48099fce6b0 not found.,encoded_authorization_message:None }
2025-03-25 18:44:43,980 - custodian.policy - INFO - policy:delete_policy_unassociated action:cbrdeletepolicy resources:1 execution_time:0.86
